name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: derailedapp/cla-assistant@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          # This token is required only if you have configured to store the signatures in a remote repository/organization
          PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          path-to-signatures: 'version1/cla.json'
          path-to-document: 'https://gist.github.com/VincentRPS/3b0f267edfa23e365b03b8bbc2f0cc6e'
          allowlist: train9
          remote-organization-name: derailedapp
          remote-repository-name: signatures
          lock-pullrequest-aftermerge: true
          custom-notsigned-prcomment: "Hello! I am your friendly Train Conductor here in station Derailed to inform you that you must sign our [Contributor License Agreement](https://gist.githubusercontent.com/VincentRPS/3b0f267edfa23e365b03b8bbc2f0cc6e/raw/3e882929a40150dc5ac94b875471ca69b36fecd6/.md) before preceding. Once you've finished reading, and agree to everything there, comment 'I have read the CLA Document and I hereby sign the CLA' so we can merge your PR!\n\nGo Fix Some Code, Train Conductor"
          custom-allsigned-prcomment: "All contributors have signed the [Contributor License Agreement](https://gist.githubusercontent.com/VincentRPS/3b0f267edfa23e365b03b8bbc2f0cc6e/raw/3e882929a40150dc5ac94b875471ca69b36fecd6/.md)! This PR is (legally) allowed to be merged!\n\nGo Break Some Code, Train Conductor"
